name: Build SHSHHelper Tweak (Manual Artifact Output)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Manually clone repo
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
          git checkout ${{ github.ref_name }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang llvm fakeroot dpkg-dev zip cmake git

      - name: Build and install ldid
        run: |
          git clone https://github.com/tpoechtrager/ldid.git
          cd ldid
          git submodule update --init
          chmod +x make.sh
          ./make.sh
          sudo cp ldid /usr/local/bin/
          cd ..

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> $GITHUB_ENV

      - name: Build the tweak
        run: |
          cd SHSHHelper
          make clean
          make package

      - name: Zip deb output
        run: |
          cd SHSHHelper/packages
          zip -r ../../../SHSHHelperOutput.zip *.deb
