name: Build SHSHHelper Tweak (Stable)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Manually clone repo
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
          git checkout ${{ github.ref_name }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang llvm fakeroot dpkg-dev zip git curl

      - name: Install ldid
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_linux_x86_64
          chmod +x ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> $GITHUB_ENV

      - name: Build the tweak
        run: |
          cd SHSHHelper
          make clean
          make package

      - name: Zip deb output
        run: |
          cd SHSHHelper/packages
          zip -r ../../../SHSHHelperOutput.zip *.deb
