name: Build SHSHHelper Tweak (Auto Release)

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发
    paths:
      - '.github/workflows/build.yml'  # 监控 build.yml 文件的变化
      - 'Tweak.xm'  # 增加对 Tweak.xm 文件的监控
      - 'control'

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境来构建

    steps:
      # 获取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      # 安装依赖（基础构建工具）
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang llvm fakeroot dpkg-dev zip git curl make jq

      # 安装 Theos
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos

      # 设置 Theos 环境变量
      - name: Export THEOS path
        run: |
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "THEOS_MAKE_PATH=~/theos/makefiles" >> $GITHUB_ENV

      # 禁用 SDK 检查并设置 Linux 构建目标
      - name: Set target to Linux and disable SDK check
        run: |
          echo "THEOS_TARGET=linux" >> $GITHUB_ENV
          echo "export THEOS_TARGET=linux" >> ~/.bashrc

      # 清理旧构建缓存
      - name: Clean previous build artifacts
        run: |
          rm -rf *.deb packages/ .theos/

      # 构建插件
      - name: Build the tweak
        run: |
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      # 列出生成的 .deb 包
      - name: List generated DEBs
        run: |
          ls -lh packages/

      # 创建 GitHub Release
      - name: Create GitHub Release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION packages/*.deb --title "SHSHHelper $VERSION" --notes "自动构建 SHSHHelper .deb 安装包"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      # 上传 .deb 到工作流 artifacts
      - name: Upload DEB to workflow artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: SHSHHelper
          path: packages/*.deb
