name: Build SHSHHelper Tweak (Auto Release)

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'Tweak.xm'
      - 'control'
      - 'Makefile'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Theos Setup Action
        uses: axs66/theos-action@main

      - name: Clean previous packages
        run: rm -f ${{ github.workspace }}/packages/*.deb

      - name: Build DEB (rootless + roothide)
        run: |
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: List generated DEBs
        run: ls -lh ${{ github.workspace }}/packages

      - name: Create GitHub Release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb --title "SHSHHelper $VERSION" --notes "自动构建 .deb 安装包"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload DEB to workflow artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: SHSHHelper
          path: ${{ github.workspace }}/packages/*.deb
