name: Build SHSHHelper Tweak (Auto Release)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 获取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # 安装依赖
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang llvm fakeroot dpkg-dev zip git curl make jq

      # 安装 ldid
      - name: Install ldid
        run: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_linux_x86_64
          chmod +x ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

      # 安装 Theos
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos

      # 安装 iOS toolchain
      - name: Install iOS Toolchain
        run: |
          mkdir -p ~/theos/toolchain
          curl -LO https://github.com/theos/toolchain-linux/releases/download/latest/toolchain.tar.xz
          tar -xf toolchain.tar.xz -C ~/theos/toolchain

      # 安装 iOS SDK
      - name: Install iOS SDK
        run: |
          mkdir -p ~/theos/sdks
          curl -LO https://github.com/theos/sdks/releases/download/20240505/iPhoneOS16.4.sdk.tar.xz
          tar -xf iPhoneOS16.4.sdk.tar.xz -C ~/theos/sdks

      # 设置 Theos 环境变量
      - name: Export THEOS path
        run: |
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "THEOS_MAKE_PATH=~/theos/makefiles" >> $GITHUB_ENV

      # 清理旧构建缓存
      - name: Clean previous build artifacts
        run: |
          rm -rf *.deb packages/ .theos/

      # 列出仓库文件，确认 Makefile 结构
      - name: List repo files before build
        run: |
          find .

      # 构建插件
      - name: Build the tweak
        run: |
          make clean
          make package

      # 打包 .deb 为 zip
      - name: Zip deb output
        run: |
          zip -r SHSHHelperOutput.zip *.deb

      # 创建 Release（如不存在）
      - name: Create GitHub Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "v1.0.0", "name": "v1.0.0", "body": "SHSHHelper tweak release"}' \
            https://api.github.com/repos/${{ github.repository }}/releases || true

      # 上传 .deb zip 到 Release
      - name: Upload .deb to Release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0.0 | jq -r .id)

          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Content-Type: application/zip" \
            --data-binary @SHSHHelperOutput.zip \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=SHSHHelperOutput.zip"
