name: Build SHSHHelper Tweak (Auto Release)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 获取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # 更新包列表并修复依赖冲突
      - name: Update package list and fix dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y --fix-broken

      # 移除冲突的 docker.io 并安装 Docker
      - name: Remove existing Docker package
        run: |
          sudo apt-get remove --purge docker.io
          sudo apt-get autoremove -y

      # 安装 Docker 使用官方方法
      - name: Install Docker using official method
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      # 验证 Docker 安装
      - name: Verify Docker installation
        run: |
          docker --version

      # 拉取 Theos Docker 镜像并构建
      - name: Build with Theos Docker
        run: |
          docker pull theos/theos  # 拉取 Theos 官方 Docker 镜像
          docker run --rm -v $(pwd):/theos theos/theos make clean  # 清理旧构建
          docker run --rm -v $(pwd):/theos theos/theos make package  # 构建插件

      # 打包 .deb 包为 ZIP
      - name: Zip deb output
        run: |
          zip -r SHSHHelperOutput.zip *.deb

      # 创建 Release（如不存在）
      - name: Create GitHub Release
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "v1.0.0", "name": "v1.0.0", "body": "SHSHHelper tweak release"}' \
            https://api.github.com/repos/${{ github.repository }}/releases || true

      # 上传 .deb zip 到 Release
      - name: Upload .deb to Release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/v1.0.0 | jq -r .id)

          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Content-Type: application/zip" \
            --data-binary @SHSHHelperOutput.zip \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=SHSHHelperOutput.zip"
