name: Build SHSHHelper Tweak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang llvm ldid fakeroot dpkg-dev zip

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> $GITHUB_ENV

      - name: Build the tweak
        run: |
          cd SHSHHelper
          make clean
          make package

      - name: Rename .deb file for output
        run: |
          cd SHSHHelper/packages
          for file in *.deb; do
            cp "$file" "../../../SHSHHelper.deb"
          done

      - name: Upload .deb package
        uses: actions/upload-artifact@v2
        with:
          name: SHSHHelper-deb
          path: SHSHHelper.deb
