name: Build SHSHHelper Tweak (Manual Artifact Output)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 手动 clone 仓库（替代 checkout@v2）
      - name: Manually clone repo
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
          git checkout ${{ github.ref_name }}

      # 安装编译依赖
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang llvm fakeroot dpkg-dev zip cmake git

      # 安装 ldid（手动构建）
      - name: Build and install ldid
        run: |
          git clone https://github.com/tpoechtrager/ldid.git
          cd ldid
          git submodule update --init
          ./make.sh
          sudo cp ldid /usr/local/bin/
          cd ..

      # 安装 Theos
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> $GITHUB_ENV

      # 编译 tweak
      - name: Build the tweak
        run: |
          cd SHSHHelper
          make clean
          make package

      # 打包成 zip 供下载
      - name: Zip deb output
        run: |
          cd SHSHHelper/packages
          zip -r ../../../SHSHHelperOutput.zip *.deb
